<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Excel;
use App\Imports\SeedImport;
use App\Models\OfferedCourseSection as OFS;
use App\Models\OfferedCourse as OF;
use App\Models\Course;

class CourseSectionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $rows = $this->importLabSections('files/2020-Summer-Lab-List.xlsx');
        
        foreach ($rows as $key => $row) {
            try {
                OFS::create([
                    'offered_course_id' => $this->getOFID($row['course']),
                    'section' => $row['section'],
                    'name' => $row['name'],
                    'email' => $row['email'],
                    'initials' => '',
                    'is_lab_faculty' => true,
                ]);
            } catch (\Throwable $th) {
                OFS::create([
                    'offered_course_id' => Course::where('code', $row['course'])->first()->offered->first()->id,
                    'section' => $row['section'],
                    'name' => $row['name'],
                    'email' => $row['email'],
                    'initials' => '',
                    'is_lab_faculty' => true,
                ]);
            }
        }

        $frs = json_decode('{
            "ACT201":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "ACT202":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "ACT301":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "ACT422":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "ACT423":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "ACT501":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "ACT502":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "ACT701":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "ANT101":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ANT102":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ANT103":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ANT203":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ANT302":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ANT311":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ANT355":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ANT376":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ARC121":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC122":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC123":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC224":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC225":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC231":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC241":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC242":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC251":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC252":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC327":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC331":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC343":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC393":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC394":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC413":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC431":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC432":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC441":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC452":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC491":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC493":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC494":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC522":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ARC541":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "BCH101":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BCH102":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BCH201":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BCH202":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BIO101":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BNG103":[{"frac":"SCHOOL OF GENERAL EDUCATION","sections":""}],
            "BTC501":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTC504":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTC519":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE101":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE102":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE103":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE201":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE202":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE203":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE204":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE302":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE303":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE304":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE306":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE307":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE308":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE310":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE317":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE401":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE402":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE403":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE404":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE405":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BTE411":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "BUS101":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "BUS201":[{"frac":"BRAC BUSINESS SCHOOL","sections":"1,2,5,6,7,8,9"},{"frac":"BRAC INSTITUTE OF LANGUAGES","sections":"3,4"}],
            "BUS202":[{"frac":"SCHOOL OF LAW","sections":""},{"frac":"BRAC BUSINESS SCHOOL","sections":"2,5,6"}],
            "BUS203":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "BUS203.1":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "BUS301":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "BUS302":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "BUS321":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "BUS502":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "BUS503":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "BUS510":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "BUS702":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "BUS704":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "BUS710":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "CEE212":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "CEE412":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "CHE101":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "CHE110":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "CHN101":[{"frac":"BRAC INSTITUTE OF LANGUAGES","sections":""}],
            "CSE101":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE110":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE111":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE161":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE220":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE221":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE230":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE250":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":"12,13,14,15,16"},{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":"1,2,3,4,5,6,7,8,9,10,11"}],
            "CSE251":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":"11,12,13,14"},{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":"1,2,3,4,5,6,7,8,9,10"}],
            "CSE260":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE310":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE320":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE321":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE330":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE331":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE340":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE341":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE350":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":"11,12,13,14"},{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":"1,2,3,4,5,6,7,8,9,10"}],
            "CSE360":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE370":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE371":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "CSE390":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE419":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE420":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE421":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE422":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE423":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE424":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE425":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE431":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE460":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":"11,12,13"},{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":"1,2,3,4,5,6,7,8,9,10"}],
            "CSE461":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE470":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE471":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE474":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE490":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE490.1":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE490.3":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE490.5":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE490.7":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE491":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE491.1":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE491.2":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE705":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE708":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE710":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE716":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "CSE799":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "DEV301":[{"frac":"BRAC DEVELOPMENT INSTITUTE","sections":""}],
            "DEV501":[{"frac":"BRAC DEVELOPMENT INSTITUTE","sections":""}],
            "DEV502":[{"frac":"BRAC DEVELOPMENT INSTITUTE","sections":""}],
            "DEV503":[{"frac":"BRAC DEVELOPMENT INSTITUTE","sections":""}],
            "DEV506":[{"frac":"BRAC DEVELOPMENT INSTITUTE","sections":""}],
            "DEV612":[{"frac":"BRAC DEVELOPMENT INSTITUTE","sections":""}],
            "DEV616":[{"frac":"BRAC DEVELOPMENT INSTITUTE","sections":""}],
            "DEV691":[{"frac":"BRAC DEVELOPMENT INSTITUTE","sections":""}],
            "DMG513":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "DMG514":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "DMG626":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ECE203":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "ECE205":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "ECE207":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "ECE221":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "ECE243":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "ECE305":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "ECE411":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "ECE481":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE362":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "ECO101":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO102":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO104":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ECO105":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO201":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO202":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO206":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO207":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO208":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO209":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO303":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO306":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO308":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO309":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO310":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO311":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO324":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO430":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO431":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO432":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO501":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "ECO501.1":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "ECO501.2":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "ECO502":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "ECO502.1":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "ECO502.2":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "ECO513":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO514":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO515":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO612":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "ECO636":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "EEE201":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE203":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE205":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE207":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE209":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE221":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE223":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE241":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE243":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE301":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE305":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE307":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE321":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE323":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE341":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE343":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE361":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "EEE365":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE411":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE413":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE421":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EEE490":[{"frac":"DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING","sections":""}],
            "EMB101":[{"frac":"SCHOOL OF GENERAL EDUCATION","sections":""}],
            "ENG091":[{"frac":"BRAC INSTITUTE OF LANGUAGES","sections":""}],
            "ENG101":[{"frac":"BRAC INSTITUTE OF LANGUAGES","sections":""}],
            "ENG102":[{"frac":"BRAC INSTITUTE OF LANGUAGES","sections":"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20"},{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":"21"}],
            "ENG103":[{"frac":"BRAC INSTITUTE OF LANGUAGES","sections":""}],
            "ENG111":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG113":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG114":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG115":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG123":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG201":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG203":[{"frac":"BRAC INSTITUTE OF LANGUAGES","sections":""}],
            "ENG213":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG217":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG221":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG301":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG319":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG332":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG334":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG358":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG364":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG366":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG404":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG414":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG434":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG465":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG490":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG604":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG615":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG620":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG642":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG645":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG647":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENG649":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "ENV101":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "ENV103":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "FIN301":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "FIN421":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "FIN423":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "FIN424":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "FIN427":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "FIN441":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "FIN501":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "FIN602":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "FIN603":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "FIN701":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "FIN731":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "FRN101":[{"frac":"BRAC INSTITUTE OF LANGUAGES","sections":""}],
            "GEO101":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "HRM501":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "HRM501.1":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "HRM501.2":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "HRM502":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "HRM610":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "HRM611":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "HST102":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "HST103":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "HST202":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "HST403":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "HST405":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "HUM101":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "HUM103":[{"frac":"SCHOOL OF GENERAL EDUCATION","sections":""}],
            "ITS510":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "LAW101":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW102":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW103":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW104":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW201":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW202":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW203":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW204":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW205":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW301":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW302":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW303":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW304":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW305":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW306":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW307":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW308":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW345":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW401":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW402":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW403":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW404":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW434":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW435":[{"frac":"SCHOOL OF LAW","sections":""}],
            "LAW447":[{"frac":"SCHOOL OF LAW","sections":""}],
            "MAT091":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT092":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT101":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT103":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT104":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "MAT105":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT110":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT120":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT123":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT203":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT211":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT215":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT216":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT221":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT222":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT311":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT316":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT350":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MAT501":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MEE344":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "MGT201":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MGT211":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MGT301":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MGT401":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MGT422":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MGT423":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MGT424":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MGT425":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MGT427":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MGT431":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MGT501":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MGT601":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MGT701":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MGT702":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MGT711":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MGT721":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MIC101":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MIC102":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MIC201":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MIC202":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MIC203":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MIC204":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MIC206":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MIC300":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MIC301":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MIC302":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MIC303":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MIC306":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MIC309":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MIC310":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MIC402":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MIC403":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MIC406":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MKT201":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MKT301":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MKT421":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MKT423":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MKT424":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MKT425":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MKT425.3":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MKT426":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MKT431":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MKT501":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MKT501.1":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MKT501.2":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MKT601":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MKT605":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MKT701":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MKT721":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MSC142":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MSC301":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MSC424":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MSC427":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MSC441":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MSC444":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MSC445":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MSC446":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MSC449":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MSC703":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MSC705":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MSC729":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "OPN501":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "OPN603":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "OPN605":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "PHI521":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "PHY101":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "PHY102":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "PHY111":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "PHY112":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "PHY115":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "PHY202":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "PHY304":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "POL101":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "PSM501":[{"frac":"INSTITUTE OF GOVERNANCE STUDIES","sections":""}],
            "PSM521":[{"frac":"INSTITUTE OF GOVERNANCE STUDIES","sections":""}],
            "PSM522":[{"frac":"INSTITUTE OF GOVERNANCE STUDIES","sections":""}],
            "PSM523":[{"frac":"INSTITUTE OF GOVERNANCE STUDIES","sections":""}],
            "PSM524":[{"frac":"INSTITUTE OF GOVERNANCE STUDIES","sections":""}],
            "PSM607":[{"frac":"INSTITUTE OF GOVERNANCE STUDIES","sections":""}],
            "PSM608":[{"frac":"INSTITUTE OF GOVERNANCE STUDIES","sections":""}],
            "PSY101":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "PSY421":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "SOC101":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "SOC390":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "STA101":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "STA201":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "STA301":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "STA501":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "TSL502":[{"frac":"BRAC INSTITUTE OF LANGUAGES","sections":""}],
            "TSL504":[{"frac":"BRAC INSTITUTE OF LANGUAGES","sections":""}],
            "TSL602":[{"frac":"BRAC INSTITUTE OF LANGUAGES","sections":""}],
            "PHR205":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PRE001":[{"frac":"BRAC INSTITUTE OF LANGUAGES","sections":""}],
            "PHR217":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHR211":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "MPH691":[{"frac":"BRAC JAMES P GRANT SCHOOL OF PUBLIC HEALTH","sections":""}],
            "PHR203":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHR412":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHR201":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "MPH531":[{"frac":"BRAC JAMES P GRANT SCHOOL OF PUBLIC HEALTH","sections":""}],
            "PSM505":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "CSE430":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "PHR108":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "CSE391":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "PHR214":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHR107":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHY110":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "SOC301":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "PHR411":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHR102":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHR213":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "MPH521":[{"frac":"BRAC JAMES P GRANT SCHOOL OF PUBLIC HEALTH","sections":""}],
            "PHR302":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHR403":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHR304":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "MPH512":[{"frac":"BRAC JAMES P GRANT SCHOOL OF PUBLIC HEALTH","sections":""}],
            "MPH690":[{"frac":"BRAC JAMES P GRANT SCHOOL OF PUBLIC HEALTH","sections":""}],
            "PHR401":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PSM502":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "PHR110":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHR310":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "MPH522":[{"frac":"BRAC JAMES P GRANT SCHOOL OF PUBLIC HEALTH","sections":""}],
            "PHR312":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHR404":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHR410":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "TSL505":[{"frac":"BRAC INSTITUTE OF LANGUAGES","sections":""}],
            "CSE100":[{"frac":"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING","sections":""}],
            "PHR103":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "MPH670":[{"frac":"BRAC JAMES P GRANT SCHOOL OF PUBLIC HEALTH","sections":""}],
            "DMG627":[{"frac":"DEPARTMENT OF ARCHITECTURE","sections":""}],
            "PHR314":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHR303":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "MPH530":[{"frac":"BRAC JAMES P GRANT SCHOOL OF PUBLIC HEALTH","sections":""}],
            "PHR311":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "MPH620":[{"frac":"BRAC JAMES P GRANT SCHOOL OF PUBLIC HEALTH","sections":""}],
            "PHR202":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "LAW425":[{"frac":"SCHOOL OF LAW","sections":""}],
            "PHR301":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "MIC308":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MKT421.2":[{"frac":"BRAC BUSINESS SCHOOL","sections":""}],
            "MIC401":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "PHR101":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "MPH541":[{"frac":"BRAC JAMES P GRANT SCHOOL OF PUBLIC HEALTH","sections":""}],
            "ENG653":[{"frac":"DEPARTMENT OF ENGLISH AND HUMANITIES","sections":""}],
            "MPH520":[{"frac":"BRAC JAMES P GRANT SCHOOL OF PUBLIC HEALTH","sections":""}],
            "PHR313":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHR305":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHR402":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHR210":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHR109":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "MPH681":[{"frac":"BRAC JAMES P GRANT SCHOOL OF PUBLIC HEALTH","sections":""}],
            "MPH700":[{"frac":"BRAC JAMES P GRANT SCHOOL OF PUBLIC HEALTH","sections":""}],
            "PHR212":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "PHY114":[{"frac":"DEPARTMENT OF MATHEMATICS AND NATURAL SCIENCES","sections":""}],
            "MPH511":[{"frac":"BRAC JAMES P GRANT SCHOOL OF PUBLIC HEALTH","sections":""}],
            "PHR204":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "MPH501":[{"frac":"BRAC JAMES P GRANT SCHOOL OF PUBLIC HEALTH","sections":""}],
            "PHR413":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "ECO305":[{"frac":"DEPARTMENT OF ECONOMICS AND SOCIAL SCIENCES","sections":""}],
            "PHR405":[{"frac":"DEPARTMENT OF PHARMACY","sections":""}],
            "DEV506":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "DEV503":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "DEV612":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "DEV301":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "DEV501":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "DEV502":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "DEV616":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "DEV691":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "PSM501":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "PSM502":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "PSM505":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "PSM521":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "PSM522":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "PSM523":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "PSM524":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "PSM607":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}],
            "PSM608":[{"frac":"BRAC INSTITUTE OF GOVERNANCE AND DEVELOPMENT","sections":""}]
        }', true);

        $rows = $this->importLabSections('files/2020-Summer-Theory-List.xlsx');

        foreach ($rows as $row) {
            $course = $this->getCourse($frs, $row['course'], $row['section']);

            if (gettype($course) != 'boolean') {
                OFS::create([
                    'offered_course_id' => $course->offered->first()->id,
                    'section' => $row['section'] == null || $row['section'] == "" ? 1 : $row['section'],
                    'name' => $row['name'],
                    'email' => $row['email'],
                    'initials' => '',
                ]);
            }
        }
    }

    public function importLabSections($file)
    {
        return Excel::toArray(new SeedImport, public_path($file))[0];
    }

    public function getCourse($frs, $code, $section)
    {
        $course = Course::where('code', $code)->get();

        if (count($course) == 1) {
            return $course->first();
        }

        if (array_key_exists($code, $frs)) {
            $fractions = $frs[$code];

            foreach ($fractions as $fraction) {
                if (gettype(strpos($fraction['sections'], $section . "")) != 'boolean') {
                    return $course->where('provider', $fraction['frac'])->first();
                }
            }
        }

        return false;
    }
}
